LANGUAGE_DICT = {
    "angular": ["angular.dev"],
    "apache": ["httpd.apache.org"],
    "apple": ["developer.apple.com"],
    "arch": ["wiki.archlinux.org"],
    "archlinux": ["wiki.archlinux.org"],
    "astro": ["docs.astro.build"],
    "babel": ["babeljs.io"],
    "babeljs": ["babeljs.io"],
    "backbone": ["backbonejs.org"],
    "backbonejs": ["backbonejs.org"],
    "bazel": ["bazel.build"],
    "bootstrap": ["getbootstrap.com"],
    "bower": ["bower.io"],
    "c++": ["en.cppreference.com"],
    "cfdocs": ["cfdocs.org"],
    "chai": ["chaijs.com"],
    "chaijs": ["chaijs.com"],
    "chef": ["docs.chef.io"],
    "clojure": ["clojuredocs.org", "clojure.org"],
    "clojuredocs": ["clojuredocs.org"],
    "codecept": ["codecept.io"],
    "codeception": ["codeception.com"],
    "codeceptjs": ["codecept.io"],
    "codeigniter": ["codeigniter.com"],
    "coffeescript": ["coffeescript.org"],
    "coldfusion": ["cfdocs.org"],
    "composer": ["getcomposer.org"],
    "cpp": ["en.cppreference.com"],
    "cppreference": ["en.cppreference.com"],
    "crystal": ["forum.crystal-lang.org"],
    "crystallang": ["forum.crystal-lang.org"],
    "css": ["lesscss.org"],
    "cypress": ["docs.cypress.io"],
    "dart": ["dart.dev"],
    "deno": ["doc.deno.land"],
    "docs": ["docs.rs"],
    "doctrine": ["doctrine-project.org"],
    "doctrineproject": ["doctrine-project.org"],
    "drupal": ["api.drupal.org"],
    "eigen": ["eigen.tuxfamily.org"],
    "electron": ["electronjs.org"],
    "electronjs": ["electronjs.org"],
    "elixir": ["elixir-lang.org"],
    "elixirlang": ["elixir-lang.org"],
    "elm": ["elm-lang.org"],
    "elmlang": ["elm-lang.org"],
    "embarcadero": ["docwiki.embarcadero.com"],
    "erlang": ["erlang.org"],
    "esbuild": ["esbuild.github.io"],
    "eslint": ["eslint.org"],
    "express": ["expressjs.com"],
    "expressjs": ["expressjs.com"],
    "f#": ["fsharp.org"],
    "fastapi": ["fastapi.tiangolo.com"],
    "flow": ["flow.org"],
    "fsharp": ["fsharp.org"],
    "getbootstrap": ["getbootstrap.com"],
    "getcomposer": ["getcomposer.org"],
    "git": ["git-scm.com"],
    "gitscm": ["git-scm.com"],
    "gnu": ["gnu.org"],
    "go": ["go.dev"],
    "graphite": ["graphite.readthedocs.io"],
    "groovy": ["groovy-lang.org"],
    "groovylang": ["groovy-lang.org"],
    "grunt": ["gruntjs.com"],
    "gruntjs": ["gruntjs.com"],
    "hammerspoon": ["hammerspoon.org"],
    "handlebars": ["handlebarsjs.com"],
    "handlebarsjs": ["handlebarsjs.com"],
    "haskell": ["haskell.org"],
    "haxe": ["api.haxe.org"],
    "hex": ["hex.pm"],
    "homebrew": ["docs.brew.sh"],
    "httpd": ["httpd.apache.org"],
    "i3": ["i3wm.org"],
    "i3wm": ["i3wm.org"],
    "influxdata": ["docs.influxdata.com"],
    "influxdb": ["docs.influxdata.com"],
    "jasmine": ["jasmine.github.io"],
    "java": ["spring.io"],
    "javascript": ["javascript.info"],
    "jekyll": ["jekyllrb.com"],
    "jekyllrb": ["jekyllrb.com"],
    "jsdoc": ["jsdoc.app"],
    "julia": ["docs.julialang.org"],
    "julialang": ["julialang.org"],
    "khronos": ["khronos.org"],
    "knockout": ["knockoutjs.com"],
    "knockoutjs": ["knockoutjs.com"],
    "kotlin": ["kotlinlang.org"],
    "kotlinlang": ["kotlinlang.org"],
    "laravel": ["laravel.com"],
    "latex": ["latexref.xyz"],
    "latexref": ["latexref.xyz"],
    "lesscss": ["lesscss.org"],
    "manpage": ["man7.org"],
    "manpages": ["man7.org"],
    "love": ["love2d.org"],
    "love2d": ["love2d.org"],
    "lua": ["lua.org"],
    "man7": ["man7.org"],
    "mariadb": ["mariadb.com"],
    "microsoft": ["learn.microsoft.com"],
    "mocha": ["mochajs.org"],
    "mochajs": ["mochajs.org"],
    "modernizr": ["modernizr.com"],
    "moment.js": ["momentjs.com"],
    "momentjs": ["momentjs.com"],
    "mongoose": ["mongoosejs.com"],
    "mongoosejs": ["mongoosejs.com"],
    "mozilla": ["developer.mozilla.org"],
    "mysql": ["dev.mysql.com"],
    "nginx": ["nginx.org"],
    "nim": ["nim-lang.org"],
    "nimlang": ["nim-lang.org"],
    "nixos": ["nixos.org"],
    "node.js": ["nodejs.org"],
    "nodejs": ["nodejs.org"],
    "npm": ["docs.npmjs.com"],
    "npmjs": ["npmjs.com"],
    "odin": ["odin-lang.org"],
    "odinlang": ["odin-lang.org"],
    "opentsdb": ["opentsdb.net"],
    "oracle": ["docs.oracle.com"],
    "pcl": ["pointclouds.org"],
    "php": ["php.net"],
    "playwright": ["playwright.dev"],
    "pointclouds": ["pointclouds.org"],
    "pony": ["stdlib.ponylang.io"],
    "ponylang": ["stdlib.ponylang.io"],
    "postgresql": ["postgresql.org"],
    "prettier": ["prettier.io"],
    "pygame": ["pygame.org"],
    "python": ["docs.python.org"],
    "pytorch": ["pytorch.org"],
    "qt": ["qt.io"],
    "qunit": ["qunitjs.com"],
    "qunitjs": ["qunitjs.com"],
    "r": ["cran.r-project.org"],
    "rlang": ["cran.r-project.org"],
    "react": ["react.dev"],
    "react native": ["reactnative.dev"],
    "react-bootstrap": ["react-bootstrap.github.io"],
    "reactbootstrap": ["react-bootstrap.github.io"],
    "reactivex": ["reactivex.io"],
    "reactnative": ["reactnative.dev"],
    "redis": ["redis.io"],
    "redux": ["redux.js.org"],
    "requirejs": ["requirejs.org"],
    "rethinkdb": ["rethinkdb.com"],
    "router": ["router.vuejs.org"],
    "rproject": ["r-project.org"],
    "ruby": ["ruby-lang.org"],
    "rubydoc": ["ruby-doc.org", "rubydoc.info"],
    "rubylang": ["ruby-lang.org"],
    "rust": ["rust-lang.org", "docs.rs"],
    "rustlang": ["rust-lang.org"],
    "rxjs": ["rxjs.dev"],
    "saltproject": ["docs.saltproject.io"],
    "saltstack": ["docs.saltproject.io"],
    "sass": ["sass-lang.com"],
    "sasslang": ["sass-lang.com"],
    "scala": ["scala-lang.org"],
    "scalalang": ["scala-lang.org"],
    "scikitimage": ["scikit-image.org"],
    "spring": ["spring.io"],
    "sqlite": ["sqlite.org"],
    "statsmodels": ["statsmodels.org"],
    "swift": ["swift.org"],
    "symfony": ["twig.symfony.com"],
    "tailwind": ["tailwindcss.com"],
    "tailwindcss": ["tailwindcss.com"],
    "tcl": ["tcl.tk"],
    "tiangolo": ["fastapi.tiangolo.com"],
    "twig": ["twig.symfony.com"],
    "typescript": ["typescriptlang.org"],
    "typescriptlang": ["typescriptlang.org"],
    "underscore.js": ["underscorejs.org"],
    "underscorejs": ["underscorejs.org"],
    "vite": ["vite.dev"],
    "vitest": ["vitest.dev"],
    "vuerouter": ["router.vuejs.org"],
    "vue": ["vuejs.org", "vuex.vuejs.org"],
    "vuejs": ["vuejs.org", "vuex.vuejs.org"],
    "vueuse": ["vueuse.org"],
    "vuex": ["vuex.vuejs.org"],
    "wagtail": ["docs.wagtail.org"],
    "webpack": ["webpack.js.org"],
    "yarn": ["yarnpkg.com"],
    "yarnpkg": ["yarnpkg.com"],
    "yii": ["yiiframework.com"],
    "yiiframework": ["yiiframework.com"],
}

ALL_CODE_TERMS = [
    "$variable",
    "@example",
    "@import",
    "@mixin",
    "@param",
    "@returns",
    "@type",
    "@typedef",
    "@variable",
    "action",
    "actor",
    "add",
    "addtest",
    "after",
    "aftereach",
    "aggregation",
    "apirouter",
    "app",
    "application",
    "argument",
    "arima",
    "array",
    "assert",
    "astro",
    "async",
    "attribute",
    "aur",
    "autograd",
    "autoload",
    "autowired",
    "await",
    "azure",
    "babelrc",
    "bean",
    "before",
    "beforeeach",
    "beforeenter",
    "begin",
    "behavior",
    "binding",
    "bindsym",
    "block",
    "branch",
    "brew",
    "browser",
    "browserwindow",
    "btn",
    "buffer",
    "build",
    "bundle",
    "button",
    "carbon",
    "card",
    "case",
    "cfelse",
    "cfif",
    "cfloop",
    "cfquery",
    "cfset",
    "channel",
    "class",
    "clone",
    "cocoa",
    "col",
    "collection",
    "color",
    "column",
    "command",
    "commit",
    "compile",
    "component",
    "computed",
    "config",
    "connect",
    "const",
    "constexpr",
    "constructor",
    "container",
    "context",
    "controller",
    "cookbook",
    "crate",
    "css",
    "data",
    "data.frame",
    "database",
    "dataloader",
    "declare",
    "deep",
    "def",
    "defer",
    "define",
    "defmacro",
    "defmodule",
    "defp",
    "del",
    "delete",
    "deno",
    "dense",
    "dependency",
    "depends",
    "derivation",
    "describe",
    "detect",
    "directive",
    "disconnect",
    "dispatch",
    "display",
    "documentclass",
    "documentroot",
    "draw",
    "dropcaches",
    "each",
    "echo",
    "effect",
    "eigen",
    "else",
    "end",
    "entity",
    "entry",
    "entrypoints",
    "enum",
    "env",
    "equal",
    "event",
    "events",
    "exec",
    "expect",
    "expire",
    "export",
    "exports",
    "extend",
    "extends",
    "fastapi",
    "feature",
    "field",
    "fieldpanel",
    "filter",
    "filters",
    "find",
    "flake",
    "flatlist",
    "flex",
    "floating",
    "font-size",
    "for",
    "foreach",
    "form",
    "format",
    "free",
    "frontmatter",
    "fsf",
    "fun",
    "func",
    "function",
    "get",
    "getter",
    "glm",
    "globals",
    "gpl",
    "grains",
    "grid",
    "helper",
    "hook",
    "hotkey",
    "hset",
    "html",
    "impl",
    "implements",
    "import",
    "include",
    "init",
    "initconfig",
    "inlinepanel",
    "insert",
    "install",
    "interface",
    "ipcmain",
    "ipcrenderer",
    "javascript",
    "join",
    "label",
    "lambda",
    "layout",
    "let",
    "library",
    "license",
    "list",
    "listen",
    "listener",
    "loader",
    "loadmodule",
    "loadnpmtasks",
    "local",
    "location",
    "locator",
    "logit",
    "love.draw",
    "love.keypressed",
    "love.load",
    "love.mousepressed",
    "love.update",
    "makepkg",
    "man",
    "map",
    "margin",
    "match",
    "matrix",
    "mdn",
    "measure",
    "measurement",
    "menu",
    "methods",
    "metric",
    "middleware",
    "minify",
    "mix",
    "mixin",
    "modal",
    "model",
    "module",
    "moment",
    "morphology",
    "mut",
    "mutation",
    "namespace",
    "navbar",
    "nested",
    "nesting",
    "nix",
    "node",
    "object",
    "objective-c",
    "observable",
    "observer",
    "office",
    "ols",
    "open",
    "opencl",
    "opengl",
    "operator",
    "optim",
    "optimizedeps",
    "option",
    "outfile",
    "output",
    "package",
    "pacman",
    "padding",
    "page",
    "parse",
    "parser",
    "partial",
    "passthrough",
    "path",
    "pclpointcloud2",
    "pillar",
    "pipe",
    "pkgbuild",
    "platform",
    "plot",
    "plugin",
    "pointcloud",
    "polyfill",
    "post",
    "powershell",
    "preset",
    "primitive",
    "printwidth",
    "private",
    "probit",
    "proc",
    "process",
    "props",
    "prototype",
    "proxy_pass",
    "public",
    "publish",
    "pull",
    "push",
    "put",
    "qapplication",
    "qmainwindow",
    "qobject",
    "qpushbutton",
    "query",
    "qwidget",
    "recipe",
    "redirect",
    "reduce",
    "reducer",
    "ref",
    "registertask",
    "remove",
    "repository",
    "request",
    "require",
    "resource",
    "response",
    "retention",
    "root",
    "route",
    "router",
    "row",
    "rule",
    "run",
    "runner",
    "scenario",
    "schema",
    "search",
    "section",
    "select",
    "semi",
    "server",
    "serverroot",
    "service",
    "set",
    "should",
    "singlequote",
    "slot",
    "software",
    "spir-v",
    "state",
    "statisticaloutlierremoval",
    "store",
    "streamfield",
    "struct",
    "stylesheet",
    "subject",
    "subscription",
    "subtract",
    "suggest",
    "super",
    "swift",
    "systemd",
    "table",
    "tabwidth",
    "tag",
    "target",
    "task",
    "tbutton",
    "tedit",
    "template",
    "tensor",
    "test",
    "text",
    "tform",
    "theme",
    "then",
    "time",
    "timer",
    "tlabel",
    "touchableopacity",
    "tpanel",
    "trait",
    "transform",
    "twig",
    "type",
    "typedef",
    "uikit",
    "uninstall",
    "update",
    "upgrade",
    "use",
    "usepackage",
    "usetabs",
    "val",
    "var",
    "vector",
    "view",
    "virtual",
    "virtualhost",
    "visual studio",
    "void",
    "voxelgrid",
    "vulkan",
    "watch",
    "webapi",
    "webgl",
    "whisper",
    "widget",
    "window",
    "windows",
    "workspace",
    "xcode",
    "yield",
]

UNIQUE_KEYWORDS = {
    "arima": ["statsmodels"],
    "astro": ["astro"],
    "autograd": ["pytorch"],
    "autowired": ["spring"],
    "azure": ["microsoft"],
    "brew": ["homebrew"],
    "carbon": ["graphite"],
    "cocoa": ["apple"],
    "cookbook": ["chef"],
    "dataloader": ["pytorch"],
    "fsf": ["gnu"],
    "glm": ["statsmodels"],
    "gpl": ["gnu"],
    "lambda": ["python"],
    "license": ["gnu"],
    "logit": ["statsmodels"],
    "mdn": ["mozilla"],
    "nix": ["nixos"],
    "nn": ["pytorch"],
    "objective-c": ["apple"],
    "office": ["microsoft"],
    "ols": ["statsmodels"],
    "opencl": ["khronos"],
    "opengl": ["khronos"],
    "optim": ["pytorch"],
    "optimizedeps": ["vite"],
    "powershell": ["microsoft"],
    "probit": ["statsmodels"],
    "proxy_pass": ["nginx"],
    "qapplication": ["qt"],
    "qmainwindow": ["qt"],
    "qobject": ["qt"],
    "qpushbutton": ["qt"],
    "qwidget": ["qt"],
    "spir-v": ["khronos"],
    "swift": ["apple"],
    "tbutton": ["embarcadero"],
    "tedit": ["embarcadero"],
    "tensor": ["pytorch"],
    "tform": ["embarcadero"],
    "tlabel": ["embarcadero"],
    "tpanel": ["embarcadero"],
    "twig": ["symfony"],
    "visualstudio": ["microsoft"],
    "vulkan": ["khronos"],
    "webapi": ["mozilla"],
    "webgl": ["khronos"],
    "whisper": ["graphite"],
    "xcode": ["apple"],
    "apirouter": ["fastapi"],
    "aur": ["arch"],
    "browserwindow": ["electron", "electronjs"],
    "cfelse": ["cfdocs", "coldfusion"],
    "cfif": ["cfdocs", "coldfusion"],
    "cfloop": ["cfdocs", "coldfusion"],
    "cfquery": ["cfdocs", "coldfusion"],
    "cfset": ["cfdocs", "coldfusion"],
    "defer": ["odin", "odinlang"],
    "defmacro": ["elixir", "elixirlang"],
    "defmodule": ["elixir", "elixirlang"],
    "defp": ["elixir", "elixirlang"],
    "documentclass": ["latex", "latexref"],
    "documentroot": ["httpd"],
    "effect": ["react", "vueuse"],
    "entity": ["doctrine", "doctrineproject"],
    "grains": ["saltproject", "saltstack"],
    "impl": ["rust", "rustlang"],
    "ipcmain": ["electron", "electronjs"],
    "ipcrenderer": ["electron", "electronjs"],
    "loadmodule": ["httpd"],
    "love.draw": ["love", "love2d"],
    "love.keypressed": ["love", "love2d"],
    "love.load": ["love", "love2d"],
    "love.mousepressed": ["love", "love2d"],
    "love.update": ["love", "love2d"],
    "makepkg": ["arch"],
    "man": ["man7"],
    "mut": ["rust", "rustlang"],
    "pacman": ["arch"],
    "passthrough": ["pcl", "pointclouds"],
    "pclpointcloud2": ["pcl", "pointclouds"],
    "pillar": ["saltproject", "saltstack"],
    "pkgbuild": ["arch"],
    "pointcloud": ["pcl", "pointclouds"],
    "pull": ["git", "gitscm"],
    "serverroot": ["httpd"],
    "statisticaloutlierremoval": ["pcl","pointclouds"],
    "systemd": ["arch",],
    "touchableopacity": ["reactnative"],
    "usepackage": ["latex"],
    "virtualhost": ["httpd"],
}